#!/usr/bin/env bash

#/Applications/MATLAB_R2015a.app/bin/matlab -nodisplay -nodesktop -nosplash -r "run Matlab/main.m; exit"
#/Applications/MATLAB_R2015a.app/bin/matlab -nojvm -nodisplay -nodesktop -nosplash -r "newMain '../woo_occupied.jpg' '../woo_empty.jpg'; exit"
time bash Matlab/newMain/for_redistribution_files_only/run_newMain.sh /Applications/MATLAB/MATLAB_Runtime/v85 "woo_occupied.jpg" "woo_empty.jpg"
#cp ../map.jpg .
time ./main woo_occupied.jpg woo_empty.jpg woo_foreign.jpg map.jpg 30
